---
- name: Add users
  hosts: servers
  become: yes

  tasks:
    - name: Make sudoers
      user:
        name: "{{ item }}"
        groups: sudo
        append: yes
      with-items:
        - johnsnow
        - aryastark
        - daenerystargaryen

    - name: Add keys
      ansible.builtin.authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '/path/to/your/public_keys/' + item + '.pub') }}"
      with_items:
        - johnsnow
        - aryastark
        -

    - name: Update apt-get
      apt: update_cache=yes

    - name: Install htop
      apt:
        name: htop
        state: present

    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present
